site_name: RKE2 - Rancher's Next Generation Kubernetes Distribution
repo_url: https://github.com/rancher/rke2
site_url: https://docs.rke2.io
strict: false
use_directory_urls: true
theme:
  name: material
  palette:
    primary: blue
  font:
    text: 'Work Sans'
  logo: 'assets/logo-stacked-white-rke2.svg'
  favicon: 'assets/favicon-32x32.png'
#google_analytics:
plugins:
  - search
  - markdownextradata: {}
markdown_extensions:
- codehilite
- admonition
- pymdownx.tabbed:
    alternate_style: true 
- pymdownx.superfences
- toc:
    permalink: true
nav:
  - index.md
  - Installation:
    - install/requirements.md
    - install/quickstart.md
    - install/ha.md
    - Install Options:
      - install/install_options/install_options.md
      - install/install_options/server_config.md
      - install/install_options/linux_agent_config.md
      - install/install_options/windows_agent_config.md
    - install/methods.md
    - install/network_options.md
    - install/containerd_registry_configuration.md
    - install/airgap.md
    - install/windows_airgap.md
    - install/linux_uninstall.md
    - install/windows_uninstall.md
  - Upgrades:
    - Overview: upgrade/upgrade.md
    - upgrade/basic_upgrade.md
    - upgrade/automated_upgrade.md
  - Security:
    - security/about_hardened_images.md
    - security/hardening_guide.md
    - security/cis_self_assessment16.md
    - security/cis_self_assessment123.md
    - security/fips_support.md
    - security/policies.md
    - security/pod_security_standards.md
    - security/selinux.md
    - security/secrets_encryption.md
  - Architecture:
    - architecture/architecture.md
  - cluster_access.md
  - backup_restore.md
  - networking.md
  - helm.md
  - advanced.md
  - subcommands.md
  - known_issues.md
