charts:
  - version: 1.16.104
    filename: /charts/rke2-cilium.yaml
    bootstrap: true
  - version: v3.28.1-build2024091000
    filename: /charts/rke2-canal.yaml
    bootstrap: true
  - version: v3.28.100
    filename: /charts/rke2-calico.yaml
    bootstrap: true
  - version: v3.28.100
    filename: /charts/rke2-calico-crd.yaml
    bootstrap: true
  - version: 1.29.006
    filename: /charts/rke2-coredns.yaml
    bootstrap: true
  - version: 4.10.401
    filename: /charts/rke2-ingress-nginx.yaml
    bootstrap: false
  - version: 25.0.000
    filename: /charts/rke2-traefik.yaml
    bootstrap: false
  - version: 25.0.000
    filename: /charts/rke2-traefik-crd.yaml
    bootstrap: false
  - version: 3.12.003
    filename: /charts/rke2-metrics-server.yaml
    bootstrap: false
  - version: v4.1.001
    filename: /charts/rke2-multus.yaml
    bootstrap: true
  - version: v0.25.601
    filename: /charts/rke2-flannel.yaml
    bootstrap: true
  - version: 1.9.000
    filename: /charts/rancher-vsphere-cpi.yaml
    bootstrap: true
  - version: 3.3.1-rancher100
    filename: /charts/rancher-vsphere-csi.yaml
    bootstrap: true
  - version: 0.2.600
    filename: /charts/harvester-cloud-provider.yaml
    bootstrap: true
  - version: 0.1.1800
    filename: /charts/harvester-csi-driver.yaml
    bootstrap: true
  - version: 1.7.202
    filename: /charts/rke2-snapshot-controller.yaml
    bootstrap: false
  - version: 1.7.202
    filename: /charts/rke2-snapshot-controller-crd.yaml
    bootstrap: false
  - version: 1.7.302
    filename: /charts/rke2-snapshot-validation-webhook.yaml
    bootstrap: false
