charts:
  - version: 1.16.500
    filename: /charts/rke2-cilium.yaml
    bootstrap: true
  - version: v3.29.1-build2024121100
    filename: /charts/rke2-canal.yaml
    bootstrap: true
  - version: v3.29.100
    filename: /charts/rke2-calico.yaml
    bootstrap: true
  - version: v3.29.100
    filename: /charts/rke2-calico-crd.yaml
    bootstrap: true
  - version: 1.36.102
    filename: /charts/rke2-coredns.yaml
    bootstrap: true
  - version: 4.10.503
    filename: /charts/rke2-ingress-nginx.yaml
    bootstrap: false
  - version: 27.0.200
    filename: /charts/rke2-traefik.yaml
    bootstrap: false
  - version: 27.0.200
    filename: /charts/rke2-traefik-crd.yaml
    bootstrap: false
  - version: 3.12.004
    filename: /charts/rke2-metrics-server.yaml
    bootstrap: false
  - version: v4.1.301
    filename: /charts/rke2-multus.yaml
    bootstrap: true
  - version: v0.26.101
    filename: /charts/rke2-flannel.yaml
    bootstrap: true
  - version: 1.9.100
    filename: /charts/rancher-vsphere-cpi.yaml
    bootstrap: true
  - version: 3.3.1-rancher800
    filename: /charts/rancher-vsphere-csi.yaml
    bootstrap: true
  - version: 0.2.600
    filename: /charts/harvester-cloud-provider.yaml
    bootstrap: true
  - version: 0.1.2100
    filename: /charts/harvester-csi-driver.yaml
    bootstrap: true
  - version: 3.0.601
    filename: /charts/rke2-snapshot-controller.yaml
    bootstrap: false
  - version: 3.0.601
    filename: /charts/rke2-snapshot-controller-crd.yaml
    bootstrap: false
  - version: 1.9.001
    filename: /charts/rke2-snapshot-validation-webhook.yaml
    bootstrap: false
