charts:
  - version: 1.18.601
    filename: /charts/rke2-cilium.yaml
    bootstrap: true
  - version: v3.31.3-build2026011900
    filename: /charts/rke2-canal.yaml
    bootstrap: true
  - version: v3.31.300
    filename: /charts/rke2-calico.yaml
    bootstrap: true
  - version: v3.31.300
    filename: /charts/rke2-calico-crd.yaml
    bootstrap: true
  - version: 1.45.201
    filename: /charts/rke2-coredns.yaml
    bootstrap: true
  - version: 4.14.301
    filename: /charts/rke2-ingress-nginx.yaml
    bootstrap: false
  - version: 39.0.000
    filename: /charts/rke2-traefik.yaml
    bootstrap: false
  - version: 39.0.000
    filename: /charts/rke2-traefik-crd.yaml
    bootstrap: false
  - version: 3.13.006
    filename: /charts/rke2-metrics-server.yaml
    bootstrap: false
  - version: v4.2.311
    filename: /charts/rke2-multus.yaml
    bootstrap: true
  - version: v0.28.002
    filename: /charts/rke2-flannel.yaml
    bootstrap: true
  - version: 1.13.000
    filename: /charts/rancher-vsphere-cpi.yaml
    bootstrap: true
  - version: 3.6.0-rancher100
    filename: /charts/rancher-vsphere-csi.yaml
    bootstrap: true
  - version: 0.2.1100
    filename: /charts/harvester-cloud-provider.yaml
    bootstrap: true
  - version: 0.1.2500
    filename: /charts/harvester-csi-driver.yaml
    bootstrap: true
  - version: 4.2.001
    filename: /charts/rke2-snapshot-controller.yaml
    bootstrap: false
  - version: 4.2.001
    filename: /charts/rke2-snapshot-controller-crd.yaml
    bootstrap: false
  - version: 0.0.0  # this empty chart addon can be removed in v1.34, after we have shipped two minor versions that have never included it.
    filename: /charts/rke2-snapshot-validation-webhook.yaml
    bootstrap: false
  - version: 0.1.000
    filename: /charts/rke2-runtimeclasses.yaml
    bootstrap: false
    takeOwnership: true
