charts:
  - version: 1.17.300
    filename: /charts/rke2-cilium.yaml
    bootstrap: true
  - version: v3.30.0-build2025051300
    filename: /charts/rke2-canal.yaml
    bootstrap: true
  - version: v3.30.001
    filename: /charts/rke2-calico.yaml
    bootstrap: true
  - version: v3.30.001
    filename: /charts/rke2-calico-crd.yaml
    bootstrap: true
  - version: 1.42.100
    filename: /charts/rke2-coredns.yaml
    bootstrap: true
  - version: 4.12.102
    filename: /charts/rke2-ingress-nginx.yaml
    bootstrap: false
  - version: 34.2.002
    filename: /charts/rke2-traefik.yaml
    bootstrap: false
  - version: 34.2.002
    filename: /charts/rke2-traefik-crd.yaml
    bootstrap: false
  - version: 3.12.200
    filename: /charts/rke2-metrics-server.yaml
    bootstrap: false
  - version: v4.2.001
    filename: /charts/rke2-multus.yaml
    bootstrap: true
  - version: v0.26.601
    filename: /charts/rke2-flannel.yaml
    bootstrap: true
  - version: 1.11.000
    filename: /charts/rancher-vsphere-cpi.yaml
    bootstrap: true
  - version: 3.3.1-rancher1000
    filename: /charts/rancher-vsphere-csi.yaml
    bootstrap: true
  - version: 0.2.1000
    filename: /charts/harvester-cloud-provider.yaml
    bootstrap: true
  - version: 0.1.2300
    filename: /charts/harvester-csi-driver.yaml
    bootstrap: true
  - version: 4.0.002
    filename: /charts/rke2-snapshot-controller.yaml
    bootstrap: false
  - version: 4.0.002
    filename: /charts/rke2-snapshot-controller-crd.yaml
    bootstrap: false
  - version: 0.0.0  # this empty chart addon can be removed in v1.34, after we have shipped two minor versions that have never included it.
    filename: /charts/rke2-snapshot-validation-webhook.yaml
    bootstrap: false
  - version: 0.1.000
    filename: /charts/rke2-runtimeclasses.yaml
    bootstrap: false
